spring:
  application:
    name: biblioteca

  datasource:
    url: jdbc:h2:mem:testdb  # Base de datos en memoria
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
    platform: h2

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update  # Crear/actualizar las tablas según las entidades
    show-sql: true

  h2:
    console:
      enabled: true  # Habilitar la consola web de H2 para acceder a la base de datos desde el navegador
      path: /h2-console
